spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-service
      username: root
      password: example
  main:
    allow-bean-definition-overriding: true
