server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PW}

logging:
  level:
    root: info
#    sql: debug
    com.itmo.se.recommendationservice: debug
