server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    export:
      defaults:
        enabled: false
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
    com.itmo.se.recommendationservice: debug

event:
  sourcing:
    snapshot-frequency: 100
    auto-scan-enabled: true
    scan-package: com.itmo